services:
  api:
    build: .
    image: argus_hack-api:local
    ports: ["8000:8000"]
    env_file: [.env]
    volumes:
      - ./:/app
      - ./data:/app/data
    command: python -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
  # uncomment if UI exists as ./ui (Vite)
  # ui:
  #   build:
  #     context: ./ui
  #     dockerfile: Dockerfile
  #   ports: ["5173:5173"]
  #   volumes:
  #     - ./ui:/app
  #   environment:
  #     - VITE_API_BASE=http://localhost:8000
  #   command: npm run dev -- --host 0.0.0.0
